config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # Nested resource
  resources :users do
    resources :goals
  end

  resource :embed, only: :update

  resources :nodes
  resources :tasks


  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  get "sign_out", to: "tasks#index"
  get "logout", to: "sessions#destroy"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  get "account/goals", to: "account#goals"
  get "account/tasks", to: "account#tasks"
  get "account/learningmap", to: "account#learningmap"
  post "goal", to: "goals#create"
  post "goals/:id/setstatus", to: "goals#setstatus"
  post "goals/:id/setpassed", to: "goals#setpassed"
  post "goals/:id/addgoal", to: "goals#addgoal"
  delete "goal", to: "goals#destroy"
  delete "task", to: "tasks#destroy"
  delete "account", to: "users#destroy"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

end

app/models/node.rb
class Node < ApplicationRecord

end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_node, only: %i[ show edit update destroy ]

  # GET /nodes or /nodes.json
  def index
    @nodes = Node.all

  end

  # GET /nodes/1 or /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes or /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to node_url(@node), notice: "Node was successfully created." }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1 or /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to node_url(@node), notice: "Node was successfully updated." }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1 or /nodes/1.json
  def destroy
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url, notice: "Node was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_node
    @node = Node.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def node_params
    params.require(:node).permit(:title, :description, :image_url, :status, :level)
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_with(model: node, class: "contents") do |form| %>
  <% if node.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>
      <ul>
        <% node.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<div id="<%= dom_id node %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= node.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= node.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image url:</strong>
    <%= node.image_url %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= node.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Level:</strong>
    <%= node.level %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this node", node, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this node', edit_node_path(node), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/nodes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing node</h1>

  <%= render "form", node: @node %>

  <%= link_to "Show this node", @node, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to nodes", nodes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/nodes/index.html.erb
<div class="container mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <h1 class="title">Nodes</h1>
  <div class="flex space-x-4"><%= link_to 'Create node', new_node_path, class: "btn-small" %></div>
  <div class="overflow-auto hidden md:block shadow-md sm:rounded-lg border-2">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="py-3 px-6">
            Title
          </th>
          <th scope="col" class="py-3 px-6">
            Description
          </th>
          <th scope="col" class="py-3 px-6">
            Action
          </th>
        </tr>
      </thead>
      <tbody>
        <% @nodes = Node.all %>
        <% @nodes.each do |node| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="py-4 px-6"><%= node.title %></td>
            <td class="py-4 px-6"><%= node.status %></td>
            <td class="py-4 px-6"><%= link_to 'Edit', edit_node_path(node), class: "btn-small"%><%= link_to 'Show', node_path(node), class: "btn-small" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/nodes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New node</h1>
  <%= render "form", node: @node %>
  <%= link_to 'Back to nodes', nodes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/nodes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @node %>

    <%= link_to 'Edit this node', edit_node_path(@node), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this node', node_path(@node), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to nodes', nodes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>