config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # Nested resource
  resources :users do
    resources :goals
  end

  resource :embed, only: :update

  resources :nodes
  resources :tasks


  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  get "sign_out", to: "tasks#index"
  get "logout", to: "sessions#destroy"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  get "account/goals", to: "account#goals"
  get "account/tasks", to: "account#tasks"
  get "account/learningmap", to: "account#learningmap"
  post "goal", to: "goals#create"
  post "goals/:id/setstatus", to: "goals#setstatus"
  post "goals/:id/setpassed", to: "goals#setpassed"
  post "goals/:id/addgoal", to: "goals#addgoal"
  delete "goal", to: "goals#destroy"
  delete "task", to: "tasks#destroy"
  delete "account", to: "users#destroy"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

end

app/models/task.rb
class Task < ApplicationRecord

  has_rich_text :content
  has_many :task_progresses, dependent: :destroy
  has_many :users, through: :task_progresses

  before_validation :sanitize_prerequisite_id

  enum level: { basics: 0, research: 1, product: 2 }, _prefix: true


  def no_pre?
    prerequisite_id.empty?
  end

  def title_with_level
    "#{title} (#{level})"
  end

  private

  def sanitize_prerequisite_id
    self.prerequisite_id = prerequisite_id.reject(&:blank?)&.uniq
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    if current_user.has_role? :admin
      @tasks = Task.all.with_rich_text_content
    else
      redirect_to account_goals_path, alert: "Not authorized"
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @task = Task.find(params[:id])
    @user = current_user
    @goal_added = current_user.tasks.exists?(@task.id)
    if current_user.tasks.exists?(@task.id) == true
      @goal_finished = current_user.task_progresses.find_by_task_id(@task.id).done
    end
    @style = "bg-white"
    @style2 = "bg-blue"
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :content, :status, {prerequisite_id: []}, :level)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, data: { controller: "trix" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5" >
    <%= form.label :prerequisite_id, "Choose prerequisite with SHIFT/CMD + click" %>
    <br>
    <%= form.collection_select :prerequisite_id, Task.all, :id, :title_with_level, {include_blank: false}, multiple: true, size: Task.all.count,  class: "block shadow rounded-md border border-gray-200 outline-none px-2 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5" >
    <%= form.label :level %>
    <br>
    <%= form.select :level, Task.levels.keys, {:include_blank => false}, class: "block shadow rounded-md border border-gray-200 outline-none px-2 py-2 mt-2 w-full" %>
  </div>
  <div class="inline_">
    <%= form.submit class: "btn-small cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= form_tag(user_goals_path(current_user)) do %>
  <%= hidden_field_tag('task_id', @task.id) %>
  <%= button_tag(class: 'btn-small', type: 'submit', hidden: @goal_added) do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
    </svg>
  <% end %>
<% end %>
<div data-controller="tasks">
  <div class="block">
    Done
    <%= form_with(model: task, class:"text-lg inline-block my-3 w-72") do |form| %>
      <%= form.check_box :completed,
              data: {
                userid: @user.id,
                id: @task.id,
                action: "tasks#toggle tasks#confetti learningmap#move"
              }, class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500",checked: @goal_finished, disabled: @goal_finished %>
    <% end %>
  </div>
  <p class="my-5">
    <%= task.content %>
  </p>
  <div class="flex justify-end items-center flex-wrap mt-6">
    <button class="btn-small" data-action="click->modal#close click->tasks#refresh">Close</button>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="w-full bg-white rounded shadow-lg p-8 m-4 mx-auto md:max-w-auto md:w-2/3">
  <h1 class="font-bold text-4xl">Editing task</h1>
  <%= render "form", task: @task %>
  <%= link_to "Show this task", @task, class: "btn-small" %>
  <%= link_to "Back to tasks", tasks_path, class: "btn-small" %>
</div>

app/views/tasks/index.html.erb
<div class="container mx-auto">
  <h1 class="title">Tasks (admin only)</h1>
  <div class="flex space-x-4"><%= link_to 'Create task', new_task_path, class: "btn-small dark:bg-gray-800 dark:text-gray-00" %></div>
  <div class="overflow-auto hidden md:block shadow-md sm:rounded-lg border-2">
    <table class="w-full text-sm text-left text-gray-500 dark:bg-gray-800 dark:text-gray-400 ">
      <% if notice.present? %>
        <p data-controller="autohide" data-autohide-class-value="opacity-0" data-autohide-delay-value="2000" class="py-1 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block transition-all ease-in-out duration-2000" id="notice"><%= notice %></p>
      <% end %>
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="py-3 px-6">
            Title
          </th>
          <th scope="col" class="py-3 px-6">
            ID
          </th>
          <th scope="col" class="py-3 px-6">
            Actions
          </th>
        </tr>
      </thead>
      <tbody>
        <% @tasks = Task.all %>
        <% @tasks.each do |task| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <% if task.level == "basics" %>
              <td class="py-4 px-6"><span class='basics-plain'><%= task.level %></span><%= task.title %></td>
            <% elsif task.level =="product" %>
              <td class="py-4 px-6"><span class='product-plain'><%= task.level %></span><%= task.title %></td>
            <% else %>
              <td class="py-4 px-6"><span class='research-plain'><%= task.level %></span><%= task.title %></td>
            <% end %>
            <td class="py-4 px-6"><%= task.id %></td>
            <td class="py-4 px-6">
              <div class="flex space-x-4">
                <%= link_to 'Edit', edit_task_path(task), class: "btn-small" %>
                <%= link_to 'Show', task, class: "btn-small",  data: { turbo_frame: 'modal' } %>
                <%= link_to "Destroy", task, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }, class: "btn-small" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="w-full bg-white rounded shadow-lg p-8 m-4 mx-auto md:max-w-auto md:w-2/3">
  <h1 class="font-bold text-4xl">New task</h1>
  <%= render "form", task: @task %>
  <%= link_to 'Back to tasks', tasks_path, class: "btn-small" %>
</div>

app/views/tasks/show.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="fixed top-12 right-0 left-0 z-50 flex justify-center"  data-controller="tasks modal"data-modal-target="container" data-action="click->modal#closeBackground">
    <div class="max-h-screen max-w-lg relative flex flex-grow">
      <div class="max-h-full max-w-lg overflow-hidden flex flex-col bg-white border shadow-sm rounded-xl">
        <div class="p-8 overflow-y-auto">
          <%= render @task %>
        </div>
      </div>
    </div>
  </div>
<% end %>