config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # Nested resource
  resources :users do
    resources :goals
  end

  resource :embed, only: :update

  resources :nodes
  resources :tasks


  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  get "sign_out", to: "tasks#index"
  get "logout", to: "sessions#destroy"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  get "account/goals", to: "account#goals"
  get "account/tasks", to: "account#tasks"
  get "account/learningmap", to: "account#learningmap"
  post "goal", to: "goals#create"
  post "goals/:id/setstatus", to: "goals#setstatus"
  post "goals/:id/setpassed", to: "goals#setpassed"
  post "goals/:id/addgoal", to: "goals#addgoal"
  delete "goal", to: "goals#destroy"
  delete "task", to: "tasks#destroy"
  delete "account", to: "users#destroy"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  rolify

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  attr_accessor :current_password

  has_secure_password

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  has_many :task_progresses, dependent: :destroy
  has_many :tasks, through: :task_progresses, dependent: :destroy

  has_many :active_sessions, dependent: :destroy
  # goals is just the name of the association (a user by nature has goals, not tasks :-))
  # has_and_belongs_to_many :goals

  # start rolify

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  def assign_default_role
    self.add_role(:student) if self.roles.blank?
  end
  # end rolify

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def unconfirmed?
    !confirmed?
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  MAILER_FROM_EMAIL = "support@adamap.ch"

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  private

  def must_have_a_role
    unless roles.any?
      assign_default_role
    end
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include RolesHelper
  before_action :authenticate_user!, only: %i[ destroy edit index]
  before_action :set_user, only: %i[ destroy edit]

  def index
    if current_user.has_role? :admin
      if params[:query].present?
        @users = User.where("email LIKE?", "#{params[:query]}%")
      else
        @users= User.all
      end
    else
      redirect_to account_goals_path, alert: 'Not authorized'
    end

    if turbo_frame_request?
      render partial: "usertable", locals: { users: @users }
    end
  end

  def create
    @user = User.new(create_user_params)
    if @user.save
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Please check your email for confirmation instructions."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def edit
    if current_user.has_role? :admin
      @active_sessions = @user.active_sessions.order(created_at: :desc)
    end
  end

  def new
    @user = User.new
  end

  def update
    @user = current_user
    @active_sessions = @user.active_sessions.order(created_at: :desc)
    respond_to do |format|
      if @user.update(update_user_params)
        format.html { redirect_to users_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def create_user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def update_user_params
    params.require(:user).permit(:name, :email, {role_ids: []}, :current_password, :password, :password_confirmation, :unconfirmed_email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, url: account_path, method: :put do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div class="my-5">
    <%= form.label :email, "Email" %>
    <%= form.email_field :email %>
    <% if current_user.has_role? :admin %>
      <div class="box pt-10" data-controller="users" data-userid="<%= @user.id %>">
        <%= form.collection_check_boxes(:role_ids, Role.all, :id, :name) do |form| %>
          <%= form.check_box class:"mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500", data: {  userid: @user.id, action: "users#setrole"} %>
          <%= form.label %>
        <% end %>
      </div>
      <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">
      <div class="box" data-controller="tasks" data-userid="<%= @user.id %>">
        <p class="font-bold text-2xl">Goals:</p>
        <%= form.collection_check_boxes(:task_ids, Task.all, :id, :title_with_level) do |form| %>
          <br>
          <%= form.check_box class:"mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500", data: {  userid: @user.id, action: "tasks#addgoal"}%>
          <%= form.label %>
          <% if form.label.include? "basics" %>
            <td class="py-4 px-6"><span class='basics-plain'>basics</span>
            <% elsif form.label.include? "research" %>
              <td class="py-4 px-6"><span class='research-plain'>research</span>
              <% else %>
                <td class="py-4 px-6"><span class='product-plain'>product</span>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= form.submit class:"btn-small cursor-pointer" %>
      <% end %>

app/views/users/_signup_form.html.erb
<%= form_with url: sign_up_path, model: @user, builder: TailwindFormBuilder, class: "mb-4 md:flex md:flex-wrap md:justify-between" do |form| %>
  <%= render partial: "shared/form_errors", locals: { object: form.object } %>
  <div class="relative z-0 mb-6 w-full group">
    <%= form.label :email %>
    <%= form.email_field :email, required: true%>
  </div>
  <div class="relative z-0 mb-6 w-full group">
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <div class="relative z-0 mb-6 w-full group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <div class="inline_">
    <%= form.submit "Sign Up", class:"btn-small cursor-pointer"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <td class="py-4 px-6"><%= user.email %></td>
    <td class="py-4 px-6"><%= user.name %></td>
    <td class="py-4 px-6"><%= user.roles.pluck(:name) %></td>
    <td class="py-4 px-6">
      <div class="flex space-x-4">
        <div><%= link_to 'Edit', edit_user_path(user), class: "btn-small" %></div>
        <div><%= link_to 'Destroy', user, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' }, class: "btn-small" %></div>
        <div><%= link_to 'Goals', account_goals_path(:id => user),  class: "btn-small" %></div>
      </td>
    </tr>
  </div>

app/views/users/_usertable.html.erb
<%= turbo_frame_tag "users" do %>
  <div class="overflow-auto hidden md:block shadow-md sm:rounded-lg border-2">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <% if notice.present? %>
        <p data-controller="autohide" data-autohide-class-value="opacity-0" data-autohide-delay-value="1000" class="py-1 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block transition-all ease-in-out duration-500" id="notice"><%= notice %></p>
      <% end %>
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="py-3 px-6">
            E-Mail
          </th>
          <th scope="col" class="py-3 px-6">
            Name
          </th>
          <th scope="col" class="py-3 px-6">
            Role
          </th>
          <th scope="col" class="py-3 px-6">
            Action
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render users %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-sm md:mx-auto">
  <p class="font-bold text-3xl">Hi 👋 <%= @user.email %></p>
  <%= render "form", user: @user %>
</div>

app/views/users/index.html.erb
<div class="container mx-auto">
  <h1 class="title">Users (admin only)</h1>
  <%= form_with(url: users_path, method: :get, data: {
  controller: "search-form", turbo_frame: "users", turbo_action: "advance"}) do |form| %>
    <%= form.label :query, "Search users", class: "block mb-2 dark:text-gray-400" %>
    <div class="space-x-3 relative z-0 mb-6 w-full group">
      <%= form.text_field :query, class: "w-1/5 shadow rounded-md border border-gray-200 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", data: {action: "input->search-form#search"} %>
      <%= form.submit "Search", class: "btn-small cursor-pointer" %>
    </div>
  <% end %>
  <%= render "usertable", users: @users %>
</div>

app/views/users/new.html.erb
<div class="w-full bg-white rounded shadow-lg p-8 m-4 md:max-w-sm md:mx-auto">
  <%= render "signup_form" %>
</div>
<%#= render "form", user: @user %>
<%#= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>