config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  # Nested resource
  resources :users do
    resources :goals
  end

  resource :embed, only: :update

  resources :nodes
  resources :tasks


  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  get "sign_out", to: "tasks#index"
  get "logout", to: "sessions#destroy"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  get "account/goals", to: "account#goals"
  get "account/tasks", to: "account#tasks"
  get "account/learningmap", to: "account#learningmap"
  post "goal", to: "goals#create"
  post "goals/:id/setstatus", to: "goals#setstatus"
  post "goals/:id/setpassed", to: "goals#setpassed"
  post "goals/:id/addgoal", to: "goals#addgoal"
  delete "goal", to: "goals#destroy"
  delete "task", to: "tasks#destroy"
  delete "account", to: "users#destroy"

  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token

  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end

end

app/models/active_session.rb
class ActiveSession < ApplicationRecord
  belongs_to :user
  has_secure_token :remember_token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/embed.rb
class Embed
  include ActiveModel::Model
  include ActiveModel::Attributes
  include GlobalID::Identification
  include ActionText::Attachable

  require "oembed"

  attribute :id

  def self.find(id)
    new(id: id)
  end

  def embedcode
    oembed.html
  end

  def oembed
    OEmbed::Providers.register_all
    OEmbed::Providers.register_fallback(
      OEmbed::ProviderDiscovery,
      OEmbed::Providers::Noembed
    )
    OEmbed::Providers.get(id)
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
end

app/models/node.rb
class Node < ApplicationRecord

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/task.rb
class Task < ApplicationRecord

  has_rich_text :content
  has_many :task_progresses, dependent: :destroy
  has_many :users, through: :task_progresses

  before_validation :sanitize_prerequisite_id

  enum level: { basics: 0, research: 1, product: 2 }, _prefix: true


  def no_pre?
    prerequisite_id.empty?
  end

  def title_with_level
    "#{title} (#{level})"
  end

  private

  def sanitize_prerequisite_id
    self.prerequisite_id = prerequisite_id.reject(&:blank?)&.uniq
  end
end

app/models/task_progress.rb
class TaskProgress < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  PASSWORD_RESET_TOKEN_EXPIRATION = 10.minutes

  attr_accessor :current_password

  has_secure_password

  before_save :downcase_email
  before_save :downcase_unconfirmed_email

  validates :unconfirmed_email, format: {with: URI::MailTo::EMAIL_REGEXP, allow_blank: true}
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}, presence: true, uniqueness: true

  has_many :task_progresses, dependent: :destroy
  has_many :tasks, through: :task_progresses, dependent: :destroy

  has_many :active_sessions, dependent: :destroy
  # goals is just the name of the association (a user by nature has goals, not tasks :-))
  # has_and_belongs_to_many :goals

  # start rolify

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  def assign_default_role
    self.add_role(:student) if self.roles.blank?
  end
  # end rolify

  def confirm!
    if unconfirmed_or_reconfirming?
      if unconfirmed_email.present?
        return false unless update(email: unconfirmed_email, unconfirmed_email: nil)
      end
      update_columns(confirmed_at: Time.current)
    else
      false
    end
  end

  def confirmable_email
    if unconfirmed_email.present?
      unconfirmed_email
    else
      email
    end
  end

  def confirmed?
    confirmed_at.present?
  end

  def reconfirming?
    unconfirmed_email.present?
  end

  def unconfirmed_or_reconfirming?
    unconfirmed? || reconfirming?
  end

  def generate_confirmation_token
    signed_id expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email
  end

  def generate_password_reset_token
    signed_id expires_in: PASSWORD_RESET_TOKEN_EXPIRATION, purpose: :reset_password
  end

  def send_password_reset_email!
    password_reset_token = generate_password_reset_token
    UserMailer.password_reset(self, password_reset_token).deliver_now
  end

  def unconfirmed?
    !confirmed?
  end

  def self.authenticate_by(attributes)
    passwords, identifiers = attributes.to_h.partition do |name, value|
      !has_attribute?(name) && has_attribute?("#{name}_digest")
    end.map(&:to_h)

    raise ArgumentError, "One or more password arguments are required" if passwords.empty?
    raise ArgumentError, "One or more finder arguments are required" if identifiers.empty?
    if (record = find_by(identifiers))
      record if passwords.count { |name, value| record.public_send(:"authenticate_#{name}", value) } == passwords.size
    else
      new(passwords)
      nil
    end
  end

  MAILER_FROM_EMAIL = "support@adamap.ch"

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  private

  def must_have_a_role
    unless roles.any?
      assign_default_role
    end
  end

  def downcase_unconfirmed_email
    return if unconfirmed_email.nil?
    self.unconfirmed_email = unconfirmed_email.downcase
  end

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Task.all
    @goal_reviewed = current_user.task_progresses.find_by_task_id(@task.id).passed
  end

  def create
    goal = Task.find(params[:task_id])
    current_user.tasks << goal
    flash[:notice] = "Goal successfully added"
    redirect_to account_learningmap_path
  end

  def destroy
    goal = Task.find(params[:task_id])
    current_user.tasks.delete(goal)
    flash[:notice] = "Goal successfully removed"
    redirect_to account_goals_path
  end

  def addgoal
    goal = Task.find(params[:id])
    @user = User.find(params[:userid])
    if params[:checked] == false
      @user.tasks.delete(goal)
    else
      @user.tasks << goal
    end
  end

  def setstatus
    @user = User.find(params[:userid])
    goal = @user.task_progresses.find_by_task_id(params[:id])
    goal.done = params[:completed]
    goal.save!
    redirect_to account_goals_path
  end

  def setpassed
    @user = User.find(params[:userid])
    goal = @user.task_progresses.find_by_task_id(params[:id])
    goal.passed = params[:reviewed]
    goal.save!
    redirect_to account_goals_path
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActionView::Base.default_form_builder = TailwindFormBuilder
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/roles_helper.rb
module RolesHelper

  def ensure_admin
    return if current_user.has_role? :admin
    redirect_to(account_goals_path)
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdaMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <nav class="flex flex-wrap items-center justify-between w-full py-4 md:py-0 px-4 text-lg text-gray-700 bg-white dark:bg-gray-800">
    <div class="container flex flex-wrap justify-between items-center mx-auto dark:bg-gray-800">
      <a href="https://www.adamap.ch" class="flex items-center">
        <div class="relative">
          <h1 class="absolute text-2xl font-extrabold top-8 left-1.5 dark:text-white">AdaMap</h1>
          <%= image_tag "logo.png" %></div>
      </a>
      <div class="flex items-center md:order-2">
        <div class="relative" data-controller="dropdown">
          <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0" class="inline-block select-none">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 cursor-pointer block dark:text-gray-200" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
          </div>
          <div data-dropdown-target="menu" class="absolute right-0 mt-2 hidden z-10 text-sm dark:bg-gray-700 dark:text-gray-200">
            <div class="bg-white shadow rounded border overflow-hidden dark:bg-gray-700 dark:text-gray-200 ">
              <%if user_logged_in?%>
                <%= link_to 'Account', account_path(:id => current_user), data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                <%= link_to 'Goals', account_goals_path(:id => current_user), data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                <%= link_to 'Learning map', account_learningmap_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-sky-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                <% if current_user.has_role? :admin %>
                  <%= link_to 'Tasks', tasks_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                  <%= link_to 'Nodes', nodes_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                  <%= link_to 'Users', users_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
                <% end %>
                <%= link_to 'Logout', logout_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
              <% else %>
                <%= link_to 'Login', login_path, data: {action: "click->dropdown#toggle"}, class: 'no-underline block px-8 py-3 border-t text-gray-900 hover:bg-sky-300 whitespace-nowrap dark:hover:bg-gray-600 dark:text-white' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <body class="flex flex-col min-h-screen dark:bg-gray-800">
    <main style="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
      <%= yield %>
      <%= turbo_frame_tag "modal" %>
    </main>
    <footer class="mt-auto p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
      <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://adamap.ch/" class="hover:underline">AdaMap</a>. All Rights Reserved.
      </span>
      <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li>
          <a href="https://github.com/mliebich/AdaMap" class="mr-4 hover:underline md:mr-6 ">About</a>
        </li>
        <li>
          <a href="https://github.com/mliebich/AdaMap/blob/main/LICENSE" class="mr-4 hover:underline md:mr-6">Licensing</a>
        </li>
        <li>
          <a href="mailto:support@adamap.ch" class="hover:underline">Contact</a>
        </li>
      </ul>
    </footer>
  </body>
</html>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message|%>
      <li class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400"><%= message %></li>
    <% end %>
  </ul>
<% end %>